<?php declare(strict_types=1);

namespace Stefna\PhpCodeBuilder\Renderer;

use Stefna\PhpCodeBuilder\FlattenSource;
use Stefna\PhpCodeBuilder\FormatValue;
use Stefna\PhpCodeBuilder\PhpEnum;
use Stefna\PhpCodeBuilder\PhpVariable;
use Stefna\PhpCodeBuilder\ValueObject\EnumBackedCase;
use Stefna\PhpCodeBuilder\ValueObject\Identifier;
use Stefna\PhpCodeBuilder\ValueObject\Type;

class Php81Renderer extends Php8Renderer
{
	protected function formatVariableModifiers(PhpVariable $variable, ?Type $type = null): array
	{
		if ($variable->isReadOnly()) {
			$line = [];
			$line[] = $variable->getAccess() ?: 'public';
			$line[] = 'readonly';
			$line[] = $this->formatTypeHint($type);
			return $line;
		}

		return parent::formatVariableModifiers($variable, $type); // TODO: Change the autogenerated stub
	}
}
